version: '3.9'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lumina
      JWT_SECRET: supersecretjwt
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lumina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
